### ISSUE TITLE
Duplicate Disney+ Collections

### ISSUE THREAD

**Issue by LimesKey** [mrbuckwheet/Plex-Meta-Manager-Config#2]
Hey @mrbuckwheet, I've still been using this Plex Meta Manager config for a while and I've been loving it. Everything is good well except one small problem,
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/85136735/6cfc5373-fbe5-43c2-874c-86f8f9d341de)
I get these duplicate Disney+ TV Show collections every so often and they have 4 movies as a poster instead of just the Disney+ logo. Do you have this problem too? Not sure exactly if this is caused by Plex or the Meta Manager config.

**Comment by mrbuckwheet** [comment]
updated the config.yml and removed the streaming category. Streaming networks now fall under main network section. this will fix shows showing up under multiple collections. I recommend to go into collections under plex setting 
![Screenshot 2023-06-08 125406](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/124317277/460f304d-4e29-4941-83a8-c1d82b52223e)
