### ISSUE TITLE
Error :)

### ISSUE THREAD

**Issue by jcdex69** [mrbuckwheet/Plex-Meta-Manager-Config#3]
Hello,

I have multiple errors : 

![Untitled](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/6a67c115-6afe-4abb-a5ec-b12c87975776)

Can you help me please :)

Thx

**Comment by jcdex69** [comment]
thx, how we can do ?

**Comment by jcdex69** [comment]
im from France GMT+1

**Comment by mrbuckwheet** [comment]
I have nextcloud which is like zoom. Will let us talk and share screens like a zoom call. You available now?

-Ken DiMicco 
 
  On Tue, Sep 19, 2023 at 1:36 PM, ***@***.***> wrote:   


thx, how we can do ?

**Comment by jcdex69** [comment]
iam on remote not on my computer, i can acces to my pc, what you want to see ?

**Comment by jcdex69** [comment]
my plex version
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/61117351-c9a9-4e7c-89a3-ca8c58f8cd14)

**Comment by jcdex69** [comment]
my files names 
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/afdd6bc8-c87d-4677-bd78-8a642b8e7642)

**Comment by jcdex69** [comment]
my library

![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/e9d43be2-3fa8-4034-bb3d-a28dfaf5c9aa)

**Comment by jcdex69** [comment]
Collections and categories work but not overlays :(

**Comment by mrbuckwheet** [comment]
https://cloud.mrbuckwheet.com/call/rpizk8co

join and i can share screen. 
- Ken DiMicco 

    On Tuesday, September 19, 2023 at 01:52:33 PM EDT, JCDenton ***@***.***> wrote:  
 
 


Collections and categories work but not overlays :(

**Comment by jcdex69** [comment]
plex error console
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/f3cf51ad-f639-43c0-8381-64eacd44593b)

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/2a2cac3a-e054-4827-970d-936eaa24a890)

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/52df22d4-6b9c-4789-9f3e-1061da42d4f3)

**Comment by jcdex69** [comment]
my python version
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/7c189020-b70d-43ed-87d8-de9cf8553bba)

**Comment by jcdex69** [comment]
i have download all and extract

![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/8ce145a2-3e67-485b-9389-45d045187d29)

**Comment by jcdex69** [comment]
what version of python do you use ?

**Comment by mrbuckwheet** [comment]
can you send the log file "meta.log"
 

    On Tuesday, September 19, 2023 at 02:22:24 PM EDT, JCDenton ***@***.***> wrote:  
 
 


i have download all and extract

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/c8abede2-dab8-4812-8106-bae00fdc7a08)

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/6e66ccec-0622-435c-887d-da402a137db9)

**Comment by jcdex69** [comment]
> can you send the log file "meta.log" On Tuesday, September 19, 2023 at 02:22:24 PM EDT, JCDenton ***@***.***> wrote: i have download all and extract — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

sure, where i can sent ?

**Comment by mrbuckwheet** [comment]
Im using docker. python version should not matter
 

    On Tuesday, September 19, 2023 at 02:24:28 PM EDT, Ken DiMicco ***@***.***> wrote:  
 
 can you send the log file "meta.log"
 

    On Tuesday, September 19, 2023 at 02:22:24 PM EDT, JCDenton ***@***.***> wrote:  
 
 


i have download all and extract

**Comment by jcdex69** [comment]
i try to launch script in administrator

**Comment by jcdex69** [comment]
same error :( 
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/cebe632b-3331-4ff6-a868-aa354961356c)

**Comment by mrbuckwheet** [comment]
check your plex token as there is a communication error. Plex is reporting "No Items found in Plex"

**Comment by jcdex69** [comment]
i check and follow this

![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/0ff1483b-3307-44bc-aacc-aeafbeda5b9e)

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/ab88f693-26ef-4823-97b6-aa404c752381)

**Comment by jcdex69** [comment]
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/2add79b2-90b9-4105-b5dd-4758d423247f)

**Comment by mrbuckwheet** [comment]
is your plex server hosted locally or are you using an Appbox Setup?

**Comment by jcdex69** [comment]
locally

**Comment by jcdex69** [comment]
i have change the token for screen :)

**Comment by mrbuckwheet** [comment]
use the main IP like 192.168.1.X instead of 127.0.0.1

**Comment by jcdex69** [comment]
i try

**Comment by mrbuckwheet** [comment]
https://metamanager.wiki/en/latest/home/kb.html

**Comment by jcdex69** [comment]
i have uncheck this
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/f7ea5c01-3688-4e08-a361-5648346abb8a)

**Comment by jcdex69** [comment]
now i can acces with the ip in my browser

**Comment by mrbuckwheet** [comment]
working now?

**Comment by jcdex69** [comment]
always in run

**Comment by jcdex69** [comment]
i tell you when its finish

**Comment by mrbuckwheet** [comment]
you can also have plex open in your web browser and you'll see it update in realtime

**Comment by jcdex69** [comment]
same error:( 
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/a4e51c21-359c-497f-bcf0-adb91653568d)

**Comment by mrbuckwheet** [comment]
Not sure why you are still getting the error. I would try using the default config file from PMM first to troubleshoot. Make a small test library with 5 or 6 movies to make sure everything is connecting correctly. Then apply my config. You can also contact PMM support for more advanced help. Sorry I could not be of more help

**Comment by jcdex69** [comment]
Thx, with default config and small library 
![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/07ca7a9c-c9cf-4737-b6da-ce83a44236f1)

**Comment by jcdex69** [comment]
with no trakt error

![image](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/assets/6523358/14db6b2b-79d2-4790-847a-315edba6bef2)

**Comment by jcdex69** [comment]
error in plex console : 

[Req#a9e25] SQLITE3:0x7ff6de7687e0, 1, no such column: Overlay in "select count(*) from (select distinct(metadata_items.id) from metadata_items left join media_items on media_items.metadata_item_id=metadata_items.id left join media_parts on media_parts.media_item_id=media_items.id where metadata_items.library_section_id in (21) and (metadata_items.id in (select taggings.metadata_item_id from taggings join tags on tags.id=taggings.tag_id where tags.id=Overlay) and metadata_items.metadata_type=1) )"

Got exception from request handler: sqlite3_statement_backend::prepare: no such column: Overlay for SQL: select count(*) from (select distinct(metadata_items.id) from metadata_items left join media_items on media_items.metadata_item_id=metadata_items.id left join media_parts on media_parts.media_item_id=media_items.id where metadata_items.library_section_id in (21) and (metadata_items.id in (select taggings.metadata_item_id from taggings join tags on tags.id=taggings.tag_id where tags.id=Overlay) and metadata_items.metadata_type=1) )

**Comment by jcdex69** [comment]
I post on plex forum :

https://forums.plex.tv/t/sqlite3-0x7ff6de7687e0-1-no-such-column-overlay-in-select-count/854279

**Comment by mrbuckwheet** [comment]
Will be closing out this error as it seems to be an issue with plex and not my pmm config. Hopefully you can get it resolved and then pmm can connect and apply the overlays

**Comment by jcdex69** [comment]
hi, i find solution, uninstall plex and start from fresh install.

restore databases ( com.plexapp.plugins.library.db / com.plexapp.plugins.library.blobs.db) and metadata folder

and now it work :)

**Comment by mrbuckwheet** [comment]
I guess you had a corrupted database in plex. Happy it works for you now enjoy!

**Comment by jcdex69** [comment]
Yes i think is because i have plex since more than 10 years and never do clean install since this time.
Thx for your help :)
