### ISSUE TITLE
Ratings not showing up

### ISSUE THREAD

**Issue by Apap0088** [mrbuckwheet/Plex-Meta-Manager-Config#4]
Is the ratings part of this? I dont see any ratings however, the collections and categories are correct

**Comment by mrbuckwheet** [comment]
Yes make sure you link your account settings in the config file for the various sites needed to pull the ratings. tmdb, trakt, mdblist. Check your logs as they will tell you what is wrong with your config and where info is missing

**Comment by Apap0088** [comment]
|
|============================================================================================================================================== Error Summary ===============================================================================================================================================|
|                                                                                                                                                                                                                                                                                                            |
| Count | Message                                                                                                                                                                                                                                                                                            |
|=======|====================================================================================================================================================================================================================================================================================================|
|    15 | Plex Error: resolution: No matches found with regex pattern (?i)2160                                                                                                                                                                                                                               |
|     9 | Overlay Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)                                                                                                                                                                                                                     |
|     6 | Overlay Error: trakt_list requires Trakt to be configured                                                                                                                                                                                                                                          |
|     6 | Overlay Error: font: /config/overlays/fonts/Adlib.ttf not found. Options: Comfortaa-Bold.ttf, Comfortaa-Light.ttf, Comfortaa-Medium.ttf, Comfortaa-Regular.ttf, Comfortaa-SemiBold.ttf, Inter-Black.ttf, Inter-Bold.ttf, Inter-ExtraBold.ttf, Inter-ExtraLight.ttf, Inter-Light.ttf, Inter-Medium.ttf, Inter-Regular.ttf, Inter-SemiBold.ttf, Inter-Thin.ttf, Roboto-Black.ttf, Roboto-BlackItalic.ttf, Roboto-Bold.ttf, Roboto-BoldItalic.ttf, Roboto-Italic.ttf, Roboto-Light.ttf, Roboto-LightItalic.ttf, Roboto-Medium.ttf, Roboto-MediumItalic.ttf, Roboto-Regular.ttf, Roboto-Thin.ttf, Roboto-ThinItalic.ttf |
|     6 | Overlay Error: font: /config/overlays/fonts/Impact.ttf not found. Options: Comfortaa-Bold.ttf, Comfortaa-Light.ttf, Comfortaa-Medium.ttf, Comfortaa-Regular.ttf, Comfortaa-SemiBold.ttf, Inter-Black.ttf, Inter-Bold.ttf, Inter-ExtraBold.ttf, Inter-ExtraLight.ttf, Inter-Light.ttf, Inter-Medium.ttf, Inter-Regular.ttf, Inter-SemiBold.ttf, Inter-Thin.ttf, Roboto-Black.ttf, Roboto-BlackItalic.ttf, Roboto-Bold.ttf, Roboto-BoldItalic.ttf, Roboto-Italic.ttf, Roboto-Light.ttf, Roboto-LightItalic.ttf, Roboto-Medium.ttf, Roboto-MediumItalic.ttf, Roboto-Regular.ttf, Roboto-Thin.ttf, Roboto-ThinItalic.ttf |
|     5 |                                                                                                                                                                                                                                                                                                    |
|     4 | Overlay Error: font: /config/overlays/fonts/Avenir_95_Black.ttf not found. Options: Comfortaa-Bold.ttf, Comfortaa-Light.ttf, Comfortaa-Medium.ttf, Comfortaa-Regular.ttf, Comfortaa-SemiBold.ttf, Inter-Black.ttf, Inter-Bold.ttf, Inter-ExtraBold.ttf, Inter-ExtraLight.ttf, Inter-Light.ttf, Inter-Medium.ttf, Inter-Regular.ttf, Inter-SemiBold.ttf, Inter-Thin.ttf, Roboto-Black.ttf, Roboto-BlackItalic.ttf, Roboto-Bold.ttf, Roboto-BoldItalic.ttf, Roboto-Italic.ttf, Roboto-Light.ttf, Roboto-LightItalic.ttf, Roboto-Medium.ttf, Roboto-MediumItalic.ttf, Roboto-Regular.ttf, Roboto-Thin.ttf, Roboto-ThinItalic.ttf |
|     2 | Config Error: Folder /config/missing does not exist                                                                                                                                                                                                                                                |
|     2 | IMDb Error: Failed to parse URL: https://www.imdb.com/search/title/?groups=golden_globe_winner                                                                                                                                                                                                     |
|     2 | IMDb Error: Failed to parse URL: https://www.imdb.com/search/title/?groups=emmy_winner                                                                                                                                                                                                             |
|     1 | Input Failed                                                                                                                                                                                                                                                                                       |
|     1 | Collection Error: trakt_list requires Trakt to be configured                                                                                                                                                                                                                                       |
|     1 | Plex Error: No Items found in Plex                                                                                                                                                                                                                                                                 |
|     1 | IMDb Error: Failed to parse URL: https://www.imdb.com/search/title/?groups=best_picture_winner                                                                                                                                                                                                     |
|     1 | IMDb Error: Failed to parse URL: https://www.imdb.com/search/title/?groups=best_director_winner                                                                                                                                                                                                    |
|     1 | IMDb Error: Failed to parse URL: https://www.imdb.com/search/title/?groups=razzie_winner                                                                                                                                                                                                           |
|     1 | Overlays Attempted on The Purge: Overlay File (1) DTS, Overlay File (2) 1080P                                                                                                                                                                                                                      |
|     1 | Overlays Attempted on The Purge: Anarchy: Overlay File (1) DTS-HD-MA, Overlay File (2) 1080P                                                                                                                                                                                                       |
|     1 | Overlays Attempted on The Purge: Election Year: Overlay File (1) DTS-HD-MA, Overlay File (2) 1080P                                                                                                                                                                                                 |
|     1 | Overlays Attempted on The Pursuit of Happyness: Overlay File (1) Dolby-Digital, Overlay File (2) 1080P                                                                                                                                                                                             |
|     1 | Overlays Attempted on Puss in Boots: Overlay File (0) Rotten Tomatoes Certified Fresh, Overlay File (1) DTS-X, Overlay File (2) 1080P                                                                                                                                                              |
|     1 | TMDb Error: No Movie found for TMDb ID 37452                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                            |
|============================================================================================================================================================================================================================================================================================================|
|                                                                                                                                                Finished Run                                                                                                                                                |
|                                                                                                                                              Version: 1.19.1                                                                                                                                               |
|                                                                                                                              Finished: 10:10:19 2023-11-05 Run Time: 2:32:07                                                                                                                               |
|============================================================================================================================================================================================================================================================================================================|
                                                   

** Press ANY KEY to close this window **

**Comment by mrbuckwheet** [comment]
Yes logs shows you are missing trakt config and you did not download the entire repository to you PMM folder. Download the entire repository and unzip. All folders are needed as stated in the readme

**Comment by mrbuckwheet** [comment]
will be marking this as closed
